name: 'Provider status checker'
description: 'Check your provider/vendor status before deplyoing to prod !'
author: 'Eugene Belyaev'
inputs:
  providers:
    description: 'List of providers/vendors'
    required: true
    default: ''
  fail_on_warning: 
    description: 'Stop workflow run on "warning" status'
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  color: 'orange'
  icon: 'globe'
