module.exports = Object.freeze({
  STATUS_OK: 0,
  STATUS_WARNING: 1,
  STATUS_ERROR: 2,
  ICON_OK: "➔",
  ICON_WARNING: "!",
  ICON_ERROR: "✘",
  SUPPORTED_PROVIDERS: [
    "aws",
    "auth0",
    "mongodb",
    "datadog",
    "heroku",
    "twilio",
    "sendgrid",
    "pendo",
    "atlassian",
    "newrelic",
    "cloudflare",
    "sentry",
    "hashicorp",
    "github",
    "snowflake",
    "npmjs"
  ],
});
